# [build]
#   publish = "public"
#
# [build.environment]
#   HUGO_VERSION = "0.74.3"
    # HUGO_BASEURL = "/"

# [context.production.environment]
# HUGO_VERSION = "0.74.3"
# HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"
#
# [context.deploy-preview]
# command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
#
# [context.deploy-preview.environment]
# HUGO_VERSION = "0.74.3"
#
# [context.branch-deploy.environment]
# HUGO_VERSION = "0.74.3"
